In [1]:
# Jupyter Notebook for the Parallel Coordinates Data

In [47]:
import pandas as pd
from datetime import datetime
csvFolder = "../csvData/"
cleaned_data = pd.read_csv("../csvData/box_office_data_cleaned.csv", index_col="season")

In [48]:
quarters = ["Q1","Q2","Q3","Q4"]
years = list(str(date) for date in range(1989,2019))
seasons=cleaned_data.loc[["Q1 1989","Q2 1989"]]
seasons_dfs = []
new_df = pd.DataFrame()
for year in years:
    for quarter in quarters:
        seasons_dfs.append(new_df.append(cleaned_data.loc[quarter + ' ' + year]))
        new_df = pd.DataFrame()
current_index = 0
year_dfs = [pd.DataFrame for i in range(30)]

# Creates the dataframe for yearly data of the movies
for i in range(30):
    year_dfs[i] = seasons_dfs[current_index].append(seasons_dfs[current_index+1:current_index+4])
    current_index += 4
    
# Creates the dataframe for top grossing movies per year in the last 30 years
top10movies_per_year = pd.DataFrame()
for df in year_dfs:
    top10movies_per_year = top10movies_per_year.append(df.nlargest(10,'gross'))

In [46]:
# Generates the csv file for top grossing movies per year in the last 30 years
top10movies_per_year.to_csv(csvFolder + "top_10_grossing_movies_per_year.csv")

In [ ]:
# Generates the csv files for yearly data of the movies
for df in year_dfs:
    df.to_csv(csvFolder + "year" + years[curr] + "_dfs.csv")

In [49]:
cleaned = cleaned_data.sort_values('release',ascending=True)

In [50]:
cleaned

,Unnamed: 0,movie,studio,gross,release,time
season,,,,,,
Q1 1989,29,Gleaming the Cube,Twentieth Century Fox,2777280.0,1989-01-13,1989-03-31
Q1 1989,66,Under the Sun of Satan,Alive Films,68765.0,1989-01-20,1989-03-31
Q1 1989,57,Paperhouse,Vestron Pictures,241278.0,1989-02-17,1989-03-31
Q1 1989,49,High Hopes,Skouras Pictures,1192322.0,1989-02-24,1989-03-31
Q1 1989,65,Powwow Highway,Warner Bros.,283747.0,1989-02-24,1989-03-31
...,...,...,...,...,...,...
Q4 2018,12933,In the Fade,Magnolia Pictures,271345.0,2018-12-27,2018-12-31
Q4 2018,12750,Stan & Ollie,Sony Pictures Classics,5470235.0,2018-12-28,2018-12-31
Q4 2018,12446,Simmba,Reliance Big Pictures,5102129.0,2018-12-28,2018-12-31
Q4 2018,12807,Film Stars Don't Die in Liverpool,Sony Pictures Classics,564877.0,2018-12-29,2018-12-31
Q4 2018,12764,The Ex-File 3: The Return of The Exes,China Lion Film Distribution,740525.0,2018-12-29,2018-12-31