In [ ]:
# Jupyter Notebook for the Parallel Coordinates Data

In [ ]:
import pandas as pd
from datetime import datetime
csvFolder = "../csvData/"
cleaned_data = pd.read_csv("../csvData/box_office_data_cleaned.csv", index_col="season")

In [ ]:
quarters = ["Q1","Q2","Q3","Q4"]
years = list(str(date) for date in range(1989,2019))
seasons=cleaned_data.loc[["Q1 1989","Q2 1989"]]
seasons_dfs = []
new_df = pd.DataFrame()
for year in years:
    for quarter in quarters:
        seasons_dfs.append(new_df.append(cleaned_data.loc[quarter + ' ' + year]))
        new_df = pd.DataFrame()
current_index = 0
year_dfs = [pd.DataFrame for i in range(30)]

# Creates the dataframe for yearly data of the movies
for i in range(30):
    year_dfs[i] = seasons_dfs[current_index].append(seasons_dfs[current_index+1:current_index+4])
    current_index += 4
    
# Creates the dataframe for top grossing movies per year in the last 30 years
top10movies_per_year = pd.DataFrame()
top20movies_per_year = pd.DataFrame()
for df in year_dfs:
#     top10movies_per_year = top10movies_per_year.append(df.nlargest(10,'gross'))
    tempdf = df.nlargest(20,'gross')
#     tempdf['movie'].unique()
#     tempdf = tempdf.nlargest(10,'gross')
    top20movies_per_year = top20movies_per_year.append(tempdf)
#     top10movies_per_year = top10movies_per_year.append(df.nlargest(20,'gross'))
#     top10movies_per_year = top10movies_per_year.append(tempdf)
# top20movies_per_year
unique_movies = top20movies_per_year['movie'].unique()
# top10movies_per_year
top20movies_per_year
# len(top20movies_per_year)
top20movies_per_year.to_csv(csvFolder + "top_20_grossing_movies_per_year.csv")

In [108]:
# Generates the csv file for top grossing movies per year in the last 30 years
# top10movies_per_year.to_csv(csvFolder + "top_10_grossing_movies_per_year.csv")
top20movies_per_year_cleaned = pd.read_csv("../csvData/top_20_grossing_movies_per_year_cleaned.csv")
top20movies_per_year_cleaned[:-145]
top20movies_per_year_cleaned = top20movies_per_year_cleaned[:-145]
top20movies_per_year_cleaned[['quarter', 'year']] = top20movies_per_year_cleaned.season.str.split(' ', expand=True)
top20movies_per_year_cleaned = top20movies_per_year_cleaned.sort_values('year')
temp_df = pd.DataFrame()
new_df = pd.DataFrame()

top10movies_per_year_cleaned = pd.DataFrame()

quarters = ["Q1","Q2","Q3","Q4"]
years = list(str(date) for date in range(1989,2019))
yearly_dfs = []
for year in years:
    temp_df = top20movies_per_year_cleaned.loc[top20movies_per_year_cleaned['year'] == year].nlargest(10,'gross')
    yearly_dfs.append(temp_df)
    temp_df = pd.DataFrame()
len(yearly_dfs)
for df in yearly_dfs:
    top10movies_per_year_cleaned = top10movies_per_year_cleaned.append(df).sort_values('year')

top10movies_per_year_cleaned.to_csv(csvFolder + "top10movies_per_year_cleaned.csv")

# top20movies_per_year_cleaned

,season,Unnamed: 0,movie,studio,gross,release,time,quarter,year
43,Q2 1989,0.0,Batman,Warner Bros.,251188924.0,1989/6/23,1989/6/30,Q2,1989
369,Q4 1989,8.0,The Little Mermaid,Walt Disney Studios Motion Pictures,84355863.0,1989/11/17,1989/12/31,Q4,1989
408,Q4 1989,10.0,The War of the Roses,Twentieth Century Fox,86888546.0,1989/12/8,1989/12/31,Q4,1989
249,Q3 1989,3.0,Parenthood,Universal Pictures,100047830.0,1989/8/2,1989/9/30,Q3,1989
101,Q4 1989,26.0,Driving Miss Daisy,Warner Bros.,106593296.0,1989/12/15,1989/12/31,Q4,1989
...,...,...,...,...,...,...,...,...,...
28,Q4 2018,12245.0,Aquaman,Warner Bros.,335061807.0,2018/12/21,2018/12/31,Q4,2018
88,Q2 2018,12237.0,Deadpool 2,Twentieth Century Fox,318491426.0,2018/5/18,2018/6/30,Q2,2018
100,Q4 2018,12238.0,Dr. Seuss' The Grinch,Universal Pictures,270620950.0,2018/11/9,2018/12/31,Q4,2018
223,Q3 2018,12240.0,Mission: Impossible - Fallout,Paramount Pictures,220159104.0,2018/7/27,2018/9/30,Q3,2018
58,Q4 2018,12246.0,Bohemian Rhapsody,Twentieth Century Fox,216428042.0,2018/11/2,2018/12/31,Q4,2018

In [ ]:
# Generates the csv files for yearly data of the movies
for df in year_dfs:
    df.to_csv(csvFolder + "year" + years[curr] + "_dfs.csv")

In [ ]:
cleaned = cleaned_data.sort_values('release',ascending=True)

In [ ]:
cleaned